# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
metadata:
  name: "{{ .managedCluster.name }}"
baseDomain: {{ .managedCluster.aws.baseDnsDomain }}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: {{ if .managedCluster.master }}{{ .managedCluster.master.replicas }}{{ else }}3{{end}}
  platform:
    aws:
{{ if .managedCluster.aws.master }}
{{ if .managedCluster.aws.master.rootVolume }}
      rootVolume:
{{ toYaml .managedCluster.aws.master.rootVolume | indent 8}}
{{end}}
{{end}}
      type: {{ if .managedCluster.aws.master }}{{ default "m5.xlarge" .managedCluster.aws.master.type }}{{ else }}m5.xlarge{{end}}
compute:
- hyperthreading: Enabled
  name: worker
  replicas: {{ if .managedCluster.worker }}{{ .managedCluster.worker.replicas }}{{ else }}3{{end}}
  platform:
    aws:
{{ if .managedCluster.aws.worker }}
      rootVolume:
{{ if .managedCluster.aws.worker.rootVolume }}
{{ toYaml .managedCluster.aws.worker.rootVolume | indent 8}}
{{end}}
{{end}}
      type: {{ if .managedCluster.aws.worker }}{{ default "m5.xlarge" .managedCluster.aws.worker.type }}{{ else }}m5.xlarge{{end}}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork: 
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: {{ .managedCluster.aws.region }}
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
{{ .managedCluster.sshPublicKey | indent 4 }}
