# Copyright Contributors to the Open Cluster Management project
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-operators-subscription
  namespace: {{ .Namespace }}
  labels:
    name: multicluster-operators-subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicluster-operators-subscription
  template:
    metadata:
      labels:
        name: multicluster-operators-subscription
    spec:
      serviceAccountName: multicluster-operators-subscription
      containers:
        - name: multicluster-operators-subscription
          image: quay.io/open-cluster-management/multicloud-operators-subscription:latest
          ports:
          - containerPort: 8443
          command:
          - /usr/local/bin/multicluster-operators-subscription
          - --sync-interval=60
          - --agent-image=quay.io/open-cluster-management/multicloud-operators-subscription:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multicluster-operators-subscription"
            - name: DEPLOYMENT_LABEL
              value: "multicluster-operators-subscription"
          resources:
              requests:
                cpu: 100m
                memory: 128Mi
