# Copyright Contributors to the Open Cluster Management project

apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: "{{ .managedCluster.name }}"
  namespace: "{{ .managedCluster.name }}"
  labels:
    cloud: {{ .managedCluster.cloud }}
    vendor: {{ .managedCluster.vendor }}
spec:
{{ if (eq .managedCluster.cloud "aws") }}
  baseDomain: {{ .managedCluster.aws.baseDnsDomain }}
{{ end }}
{{ if (eq .managedCluster.cloud "azure") }}
  baseDomain: {{ .managedCluster.azure.baseDnsDomain }}
{{ end }}
{{ if (eq .managedCluster.cloud "gcp") }}
  baseDomain: {{ .managedCluster.gcp.baseDnsDomain }}
{{ end }}
{{ if (eq .managedCluster.cloud "vsphere") }}
  baseDomain: {{ .managedCluster.vsphere.baseDnsDomain }}
{{ end }}
  clusterName: "{{ .managedCluster.name }}"
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 2
  installed: false
  platform:
{{ if (eq .managedCluster.cloud "aws") }}
    aws:
      region: {{ .managedCluster.aws.region }}
{{ end }}
{{ if (eq .managedCluster.cloud "azure") }}
    azure:
      baseDomainResourceGroupName: {{ .managedCluster.azure.baseDomainRGN }}
      region: {{ .managedCluster.azure.region }}
{{ end }}
{{ if (eq .managedCluster.cloud "gcp") }}
    gcp:
      region: {{ .managedCluster.gcp.region }}
{{ end }}
{{ if (eq .managedCluster.cloud "vsphere") }}
    vsphere:
      cluster: {{ .managedCluster.vsphere.cluster }}
      certificatesSecretRef:
        name: {{ .managedCluster.name }}-vsphere-certs
      vCenter: {{ .managedCluster.vsphere.vcenter }}
      datacenter: {{ .managedCluster.vsphere.datacenter }}
      defaultDatastore: {{ .managedCluster.vsphere.datastore }}
      network: {{ .managedCluster.vsphere.network }}
{{ end }}
      credentialsSecretRef:
        name: "{{ .managedCluster.name }}-creds"
  provisioning:
    installConfigSecretRef:
      name: {{ .managedCluster.name }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .managedCluster.name }}-ssh-private-key
    imageSetRef:
      name: {{ include "ocpImage" . | indent 8 }}
  pullSecretRef:
    name: {{ .managedCluster.name }}-pull-secret
